logging:
  level: INFO
  loggers:
    com.chrisgilbert: DEBUG
database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: secret
  url: jdbc:postgresql://localhost:5432/postgres
  properties:
    charSet: UTF-8

  maxWaitForConnection: 1s
  validationQuery: "/* Checkout Health Check */ select 1"
  validationQueryTimeout: 3s
  minSize: 2
  maxSize: 10
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1s
